### ISSUE TITLE
Suggestions: Prev/Next from Font View

### ISSUE THREAD

**Issue by gorjious** [mekkablue/MasterStepper#1]
Would it make sense to change the stepper to cycle through the glyphs in Font View? If not by default, then maybe an option to change to that. I have a smart filter for only outlines so that is usually what I am cycling through.

**Comment by mekkablue** [comment]
Yes I have something planned for when you have Shift held down. (Same shortcut as in the bult-in _Show Next/Previous Glyph_)

As for the selection of masters… not sure yet. Will keep for later. (Should be a separate issue though.)
